### ISSUE TITLE
Add another Language for Erbele (eg. Korean :D )

### ISSUE THREAD

**Issue by sople1** [abentele/Erbele#31]
(sorry for my english)

oh, glad to your decide of continuing project. :D 
i've worked korean l10n file but i couldn't merge cause by discontinued.
but Erbele is working now, so i want to merge file for your project.

if you want, i will work for your project. how do you think?

**Comment by abentele** [comment]
nice to hear that someone else on the other side of the world uses Erbele, and wants to contribute to Erbele ;-)

There would be several ways to add the korean language:
- because of "Erbele" originally was "Smultron", and Smultron already had a korean i18n file, you could technically integrate it from there, make it work, and you could review all texts and fix wrong texts
- you could integrate your language files into Erbele

For both to achieve, you may fork my project, integrate your stuff, make it work, and after that create a pull request. Then I would integrate your changes (after a small review) and create a new release.

If it would be too hard for you, I would propose to integrate it by myself. Therefore send me your files. I would appreciate if you would do a final check to assure quality.

Thanks in advance!

**Comment by abentele** [comment]
Feel free to contribute your bug fixes or features to this project (by creating pull requests) - I will integrate everything that would be useful. But talk with me before implementing things, because I would like to be the person who asures product quality.

**Comment by abentele** [comment]
also see #23

**Comment by abentele** [comment]
closed because of inactivity
