### ISSUE TITLE
Session save during restart/logout

### ISSUE THREAD

**Issue by iCr** [abentele/Erbele#51]
Any chance to get it implemented?

**Comment by abentele** [comment]
There is already a feature for stored sessions: projects.
Use File > New Project to create one. In the project file, opened files are saved. To restore after restart/logout, re-open the project file.

If this doesn't solve your requirements, please describe it in more detail.

**Comment by iCr** [comment]
No, we are talking about the standard function of saving state during logout.
https://apple.stackexchange.com/questions/375746/how-to-read-and-manipulate-library-saved-application-state-com-apple-finder-sa

**Comment by abentele** [comment]
accepted - I think it would be worth to implement.

**Comment by mgrn0** [comment]
since this just bit me today, too - are there any plans to get this into Erbele?

**Comment by abentele** [comment]
The requirement of this issue is not clear. Sorry for the "accepted" note in my previous post - if I look again on this issue, there is no detailed description about the requirement.

State is already saved by Erbele when closing it, and restored when starting Erbele.
For example, Erbele re-opens files and restores the font size etc. when starting Erbele, as well as all other settings which can be changed in the settings dialog.
I personally don't miss anything, and there is no known bug related to state restoration at all.

So which state do you mean in detail?
If you cannot describe, I will close this issue with no resolution.

**Comment by abentele** [comment]
as the issue describes no requirements, it's not clear what should be done.

Therefore I close this ticket.
