### ISSUE TITLE
manual download

### ISSUE THREAD

**Issue by phloggu** [abentele/Erbele#54]
Please provide a manual download of Erbele outside of the AppStore again.

It used to be possible to download and install Erbele manually. This option was taken a few years ago. Now, to download and install Erbele, you need to have an Apple-ID with all disadvantages this brings in. Since there is no home brew, fink or MacPorts  package, could you please provide a way to download and install Erbele again? Thank you very much.

**Comment by abentele** [comment]
No, I will not.

Manual installation provided by the Sparkle lib is much more complex to maintain and - compared to publishing apps via Mac App Store - has many disadvantages related to security, release automation, marketing and app distribution. Maintaining manual download in Erbele costs me a lot of time which I can spend better in bug fixing and other topics. Furthermore, Apple provides extensive download and conversion rate statistics which are of interest for me.

Apple ID brings disadvantages? Really? To be honest, I think this must be an opinion of very few people in the world. If this is your opinion - ok, but then don't opt for Erbele, or build Erbele from Sourcecode by yourself (which is a really simple task with Xcode which is for free). There are alternatives which provide a manual download.

Years ago, I tried to add Erbele to Homebrew, with no success because of the maintainers of Homebrew rejected my request (see ticket #26). 

For this reasons I highly prefer Mac App Store over third party options like Home Brew, Fink or MacPorts or manual downloads.

**Comment by phloggu** [comment]
If your build environment can't produce a DMG automatically, I see the point that it is too much work for you for every release. BTW: I did not ask to give up the AppStore, I just asked to add a manual download possibility in addition.

Regarding Ticket #26: Would this still be an option for you, if the Homebrew crew would be open to receive Erbele?

**Comment by abentele** [comment]
Distribution of apps is a very complex task if you take it serious - it's not only about producing a DMG automatically, as I already tried to explain. Apple already provides solutions for all challenges of app distribution.

Home Brew, Fink or MacPorts don't provide equivalent services, while Apple decided for security and quality of apps and ensured it via app reviews and a secure infrastructure from the very beginning. Typical Mac users like the simplicity and security of Mac App Store and many don't even know Home Brew, Fink or MacPorts.

Therefore I prefer App Store over Home Brew, Fink or MacPorts. I will not provide different distribution types because it would be way too much effort with no real advantages.
